site_name: HomingCast
site_url: https://lolekic.github.io/HomingCast-API/
repo_url: https://github.com/Lolekic/HomingCast-API
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: Missile.png
  favicon: Missile.ico
  palette: 
    scheme: slate
    primary: blue grey
    accent: deep purple
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      check_paths: true
      url_download: false
      url_max_size: 33554432
      url_timeout: 10
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
nav:
  - HomingCast [Modern]:
    - Guide: NEW/index.md
    - Methods: NEW/Methods.md
    - Settings: NEW/Settings.md
    - States: NEW/States.md
    - Callbacks: NEW/Callbacks.md
    - Physics: NEW/Physics.md
    - Config: NEW/Config.md
  - HomingCast [Legacy]:
    - Guide: OLD/index.md
    - Caster: OLD/Caster.md
    - Properties: OLD/Properties.md
    - Custom Trajectories: OLD/CustomTrajectories.md
    - Physics Simulation: OLD/Physics.md
    - Parallel Simulation [REMOVED]: OLD/Parallel.md
    - InfoCast:
        - InfoCast: OLD/InfoCast.md
        - Methods: OLD/Methods.md
  - Updates: Updates.md